import { SkillCategory } from './types';

export const skills: SkillCategory[] = [
  {
    name: 'Cloud',
    skills: [
      'Azure (AZ-104)',
      'Azure VNet',
      'Azure NSG',
      'Azure VPN Gateway',
      'Entra ID',
      'AWS VPC',
      'AWS S3',
      'CloudFront',
      'Route 53',
      'ACM',
      'AWS IAM',
      'Google Cloud',
    ],
  },
  {
    name: 'IaC & Servers',
    skills: [
      'Terraform',
      'GitHub Actions',
      'Git',
      'Bash',
      'Linux (Ubuntu, CentOS)',
      'VMware ESXi',
      'Dell PowerEdge',
    ],
  },
  {
    name: 'Networking',
    skills: [
      'Cisco IOS',
      'OSPF',
      'EIGRP',
      'BGP',
      'VLAN/STP',
      'IPsec VPN',
      'WAN/LAN design',
      'Fortinet FortiGate',
      'Aruba Instant On',
      'Ruijie',
      'Cisco Wireless',
    ],
  },
  {
    name: 'Monitoring & Ops',
    skills: [
      'Zabbix',
      'Cacti',
      'MRTG',
      'FastNetMon',
      'PingPlotter',
      'Oxidized',
      'NetBox',
      'Snipe-IT',
      'Jira Service Management',
      'ITIL',
      'Root-cause analysis',
      'SOP authoring',
    ],
  },
  {
    name: 'Endpoint',
    skills: ['Hexnode MDM', 'Microsoft 365', 'Windows', 'macOS'],
  },
];
